function(setup_duo DUO_SDK_VAR)
  set(DUO_SDK_PATH "${CATKIN_DEVEL_PREFIX}/${CATKIN_PACKAGE_LIB_DESTINATION}/DUO_SDK/")
  set(SETUP_SCRIPT "${PROJECT_SOURCE_DIR}/cmake/setup_duo")
  execute_process(
    COMMAND ${SETUP_SCRIPT} ${DUO_SDK_PATH}
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})

  set(${DUO_SDK_VAR} ${DUO_SDK_PATH} PARENT_SCOPE)
endfunction()
